### ISSUE TITLE
Make a new Impostor function 

### ISSUE THREAD

**Issue by DeltaCoderr** [DevSnowflake/canvacord#40]
I had a new idea about this function which will generate an image and replace the "[REDACTED] was the Imposter" with the name, the user specifies just like other commands of trigger and fire. 
An Example Image can be found below - 
![ejected](https://user-images.githubusercontent.com/51528076/96236210-5be47f80-0fb9-11eb-8ce1-058734dff03d.png)

**Comment by zyrouge** [comment]
Thats so nice, looking forward on implementing that!

**Comment by DeltaCoderr** [comment]
Anybody gonna implement this?

**Comment by Snowflake107** [comment]
yeah

**Comment by DeltaCoderr** [comment]
alright, looking forward to this one 👍🏻

**Comment by AkiaCode** [comment]
How about being able to change the character?

**Comment by udit2303** [comment]
Could Also add `Delta was not the impostor`

**Comment by zyrouge** [comment]
Done in 5c0d998, released on v6
