### ISSUE TITLE
Add typescript typings

### ISSUE THREAD

**Issue by pikokr** [DevSnowflake/canvacord#43]
I have trouble on using canvacord on typescript

How about adding typings for typescript users?

**Comment by ItzMeRM** [comment]
@zyrouge Get to work lol

**Comment by AkiaCode** [comment]
@ItzMeRM Can I do it together?

**Comment by ItsDiscordUser** [comment]
Feel free to contribute :)

**Comment by pikokr** [comment]
🤔

**Comment by Snowflake107** [comment]
oh yeah, planned for v6 @pikokr

**Comment by DevAndromeda** [comment]
available on the latest release
