### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Drelaky** [DevSnowflake/canvacord#45]
![image](https://user-images.githubusercontent.com/53569746/97808065-c3aaf380-1c64-11eb-951f-c88d68436536.png)
why dont load the font? I install my pc basic font (Manrope)

**Comment by Drelaky** [comment]
Can anyone help?

**Comment by Drelaky** [comment]
the code: 
![image](https://user-images.githubusercontent.com/53569746/97901463-844fd600-1d3c-11eb-8fb0-53a6083da747.png)

install moduls: 
![image](https://user-images.githubusercontent.com/53569746/97901512-96ca0f80-1d3c-11eb-8b30-2d228d987059.png)

**Comment by Snowflake107** [comment]
@Drelaky see **[canvas/#1164](https://github.com/Automattic/node-canvas/issues/1164)**

**Comment by Drelaky** [comment]
But i install the font family.

**Comment by Drelaky** [comment]
Sorry but I don't understand canvas just your modules or canvacord. :/

**Comment by ItsDiscordUser** [comment]
Please open your issue **[here](https://github.com/Automattic/node-canvas)**
