### ISSUE TITLE
Can't install

### ISSUE THREAD

**Issue by PetyXbronCZ** [DevSnowflake/canvacord#49]
Hello,
Im discord.js beginner and I fell in love with your module.

But, when I wanted to install it. It told me "WARN Using request for node-pre-gyp https download" 
Actually, I tried to install node-pre-gyp but when I deployed my code to my hosting Heroku, it said me that "Build Failed".

Do you know something about this problem please? I just want to have cool rank card, but I seem to be more of an idiot who missed something. I am sorry

**Comment by Snowflake107** [comment]
Please check **[https://github.com/Automattic/node-canvas/wiki/Installation%3A-Heroku](https://github.com/Automattic/node-canvas/wiki/Installation%3A-Heroku)**

**Comment by PetyXbronCZ** [comment]
Thanks for your reply. That's all what I wanted

**Comment by Aktindo** [comment]
hey, it happened to me too. It seems like you are committing the node_modules folder too. Which is resulting in the issue.
Make a gitignore and in that, put node_modules or whatever the node modules folder name is. Commit again and that should help

**Comment by Aktindo** [comment]
note: you need to have git installed

**Comment by Snowflake107** [comment]
closing this

**Comment by KyloDev** [comment]
bitch
