### ISSUE TITLE
Jail method issue

### ISSUE THREAD

**Issue by TheGamer456YT** [DevSnowflake/canvacord#51]
If you provide 2 images when using the "jail" method, it turns the image gray. 

Example: 
```js
await require("canvacord").Canvas.jail(message.author.avatarURL({format: "png"}), message.author.avatarURL({format: "png"}))
```
Returns this image:
![](https://media.discordapp.net/attachments/773606896329818144/782573925694570506/file.jpg)
But my profile picture is https://cdn.discordapp.com/avatars/248878605147308033/a_02291e8f0e0cddf905f580e6a2d22982.webp

The jail method only checks if the second parameter is a truthy/falsy value, and dosen't check if it's a boolean.

**Comment by Snowflake107** [comment]
yeah, if something with `not falsy` value is provided as parameter (for those who take boolean), the param is set to `true`
