### ISSUE TITLE
Question: Welcome card

### ISSUE THREAD

**Issue by PetyXbronCZ** [DevSnowflake/canvacord#53]
Hello, can I ask please?
I love makin' the rank card, but I want to ask, if I can make a welcome card, with canvacord.
If yes, can you give me example please? Im using heroku, so the normal canvas is not way for me.

**Comment by Snowflake107** [comment]
First of all, canvacord depends upon **[canvas](https://github.com/Automattic/node-canvas)**.

To use `welcome card` with canvacord, you need to install another module: **[discord-canvas](https://npmjs.com/package/discord-canvas)**.

Follow this documentation page for welcomer methods: **[https://www.discord-canvas.net/functions/welcome](https://www.discord-canvas.net/functions/welcome)**

For example, use something like this:

```js
const { Welcomer } = require("canvacord");

const card = new Welcomer()
    // discord-canvas methods here, don't use .toAttachment()

card.build()
    .then(buffer => message.channel.send(new Discord.MessageAttachment(buffer, "welcome.png")));
```

# Preview
![image](https://user-images.githubusercontent.com/46562212/102103112-af0d6e00-3e54-11eb-8c5c-a4da1ff7646f.png)

**Comment by PetyXbronCZ** [comment]
This code isn't working, without errors
```
bot.on('guildMemberAdd', async member => {
    const { Welcomer } = require("canvacord");

        const card = new Welcomer()
        .setUsername(member.user.username)
        .setDiscriminator(member.user.discriminator)
        .setMemberCount(member.guild.memberCount.toLocaleString())
        .setGuildName(member.guild.name)
        .setAvatar(member.user.displayAvatarURL())
        .setColor("border", "#eb26dd")
        .setColor("username-box", "#eb26dd")
        .setColor("discriminator-box", "#eb26dd")
        .setColor("message-box", "#eb26dd")
        .setColor("title", "#eb26dd")
        .setColor("avatar", "#eb26dd")
        .setText("member-count", "- {count}x člen")
        .setText("title", "welcome")
        .setText("message", "vítej na SuroCraftu")


        card.build()
            .then(buffer => bot.channels.cache.get(welcome).send(new Discord.MessageAttachment(buffer, "welcome.png")));
});
```

**Comment by Snowflake107** [comment]
it should throw error for using `webp` format of avatar: `member.user.displayAvatarURL()`

Use

```js
member.user.displayAvatarURL({ format: "png" })
```

**Comment by PetyXbronCZ** [comment]
Working, thanks! 😃
![image](https://user-images.githubusercontent.com/35902119/102262230-112ca880-3f13-11eb-9cd2-a0f301e89351.png)

**Comment by PetyXbronCZ** [comment]
lol, forgot g in back**g**round, my english is bad

**Comment by ApeX00** [comment]
hey , the link you have is unreachable , and I want welcome card, how can I make it?pls

**Comment by PetyXbron** [comment]
> hey , the link you have is unreachable , and I want welcome card, how can I make it?pls
> 
> 
> 

Just read the message from Snowflake
https://github.com/DevSnowflake/canvacord/issues/53#issuecomment-744532186

**Comment by Dragonizedpizza** [comment]
> const welcome = "my channel id"
> 
> bot.on('guildMemberAdd', async member => {
>     const { Welcomer } = require("canvacord");
> 
>         const card = new Welcomer()
>         .setUsername(member.user.username)
>         .setDiscriminator(member.user.discriminator)
>         .setMemberCount(member.guild.memberCount.toLocaleString())
>         .setGuildName(member.guild.name)
>         .setAvatar(member.user.displayAvatarURL())
>         .setColor("border", "#eb26dd")
>         .setColor("username-box", "#eb26dd")
>         .setColor("discriminator-box", "#eb26dd")
>         .setColor("message-box", "#eb26dd")
>         .setColor("title", "#eb26dd")
>         .setColor("avatar", "#eb26dd")
>         .setText("member-count", "- {count}x člen")
>         .setText("title", "welcome")
>         .setText("message", "vítej na SuroCraftu")
> 
> 
>         card.build()
>             .then(buffer => bot.channels.cache.get(welcome).send(new Discord.MessageAttachment(buffer, "welcome.png")));
> });

@Snowflake107 where is Discord-Canvas used in this?
