### ISSUE TITLE
Progress Bar Bugged

### ISSUE THREAD

**Issue by 0Zinc** [DevSnowflake/canvacord#54]
The progress bar for the rank card seems bugged, rather than showing the progress to the next level using the whole bar, it shows progress to the next level only using the last 10% of the bar. So if you had 18000XP and that was level 19, and level 20 was 20000XP, you would expect the bar to be very small since you are only 1% of the way there, but the bar appears as if you are 90% of the way there

**Comment by Snowflake107** [comment]
something is wrong with your xp system, canvacord is fine

**Comment by 0Zinc** [comment]
@Snowflake107 The current XP and XP required appear fine, it's just the bar. Am I supposed to set the bar percentage?

**Comment by Snowflake107** [comment]
Canvacord automatically calculates your progressbar length by `currentXP` and `requiredXP` that you've provided.

**[Click here to view](https://github.com/DevSnowflake/canvacord/blob/main/src/Rank.js#L631)**

If we get multiple reports from other people on this topic, we will take it as a bug report. For now, it's more likely to be xp system bug.

**Comment by zyrouge** [comment]
> The progress bar for the rank card seems bugged, rather than showing the progress to the next level using the whole bar, it shows progress to the next level only using the last 10% of the bar. So if you had 18000XP and that was level 19, and level 20 was 20000XP, you would expect the bar to be very small since you are only 1% of the way there, but the bar appears as if you are 90% of the way there

Canvacord does not depend on rank thus calculates directly from the XP. You can try providing the deduced values (current as the maximum xp of the rank minus current maximum XP and required as maximum XP of the rank minus the maximum xp of the previous rank) by calculating for the current rank. Thus I don't feel like this is an issue with the Canvacord and thus can be resolved from the user's side without adding it into Canvacord which is redundant. Happy Coding :)!
