### ISSUE TITLE
Bot doesn´t send Image, no Error

### ISSUE THREAD

**Issue by L3-N0X** [DevSnowflake/canvacord#70]
I created a XP system and want to send the Rank canva into the chat, but i get no error and also no message in the chat...
My code is this:
```javascript
let rank = new canvacord.Rank()
      .setAvatar(img)
      .setCurrentXP(xpget[ID], "#422711")
      .setRequiredXP(xptolvl, "#422711")
      .setProgressBar("#422711", "COLOR")
      .setLevelColor("#422711")
      .setRankColor("#422711")
      .setUsername(username, "#422711")
      .setBackground("IMAGE","https://i.imgur.com/yip3DIY.png");
    rank.build()
      .then(buffer => {
        message.channel.send(buffer);
        let attachment = new Discord.MessageAttachment(buffer, "Stammtisch_XP.png");
        message.channel.send(attachment);
      });
```

Is there a order of the .set Methods necessary? Or what is the Problem? I tried to send a simple message in the .then Method, but it wouldn´t be send too.

**Comment by Snowflake107** [comment]
You should remove `message.channel.send(buffer);` and looks like your code is not executed at all!?

**Comment by L3-N0X** [comment]
Oh, that message.channel.send(buffer); was just for testing and I forgot to remove it...
The Code before the build Method and after the build Method is executed, but everything I write in the build method won't be executed. The code is in an if clause, which checks which command I wrote in the chat, and I set the ID to the message.author or to the mentioned user. The Image I set also too the message.author or the mentioned user. I will send more of my code in a few hours, I am on my smartphone right now...
Thanks for the quick response

**Comment by L3-N0X** [comment]
```javascript
else if (command === "xpget") {
    
    // SET TAGGED ID
    let targetMember = message.mentions.members.first();
    if (targetMember) {
      var img = targetMember.avatarURL;
      var username = targetMember.username;
    } else {
      var img = message.author.avatarURL;
      var username = message.author.username;
    }
    message.channel.send(`Der User <@${ID}> ist derzeit LEVEL ${lvlget[ID]}! \n${xpget[ID]} / ${xptolvl} XP für LEVEL ${lvlget[ID] + 1}!`);

    let rank = new canvacord.Rank()
      .setAvatar(img)
      .setBackground("IMAGE","https://i.imgur.com/yip3DIY.png")
      .setCurrentXP(xpget[ID], "#422711")
      .setLevel(lvlget[ID])
      .setLevelColor("#422711")
      .setRequiredXP(xptolvl, "#422711")
      .setProgressBar("#422711", "COLOR")
      .setRankColor("#422711")
      .setUsername(username, "#422711");

    rank.build()
      .then(buffer => {
        message.channel.send(buffer);
        let attachment = new Discord.MessageAttachment(buffer, "Stammtisch_XP.png");
        message.channel.send(attachment);
      });
  }


```

**Comment by udit2303** [comment]
> ```js
> else if (command === "xpget") {
>     
>     // SET TAGGED ID
>     let targetMember = message.mentions.members.first();
>     if (targetMember) {
>       var img = targetMember.avatarURL;
>       var username = targetMember.username;
>     } else {
>       var img = message.author.avatarURL;
>       var username = message.author.username;
>     }
> 
>     let rank = new canvacord.Rank()
>       .setAvatar(img)
>       .setBackground("IMAGE","https://i.imgur.com/yip3DIY.png")
>       .setCurrentXP(xpget[ID], "#422711")
>       .setLevel(lvlget[ID])
>       .setLevelColor("#422711")
>       .setRequiredXP(xptolvl, "#422711")
>       .setProgressBar("#422711", "COLOR")
>       .setRankColor("#422711")
>       .setUsername(username, "#422711");
> 
>     rank.build()
>       .then(buffer => {
>         let attachment = new Discord.MessageAttachment(buffer, "Stammtisch_XP.png");
>         message.channel.send(attachment);
>       });
>   }
> ```

From what I've read, I think the code isn't getting executed. Can you try console logging some stuff(anything) for the command?

**Comment by L3-N0X** [comment]
Where to log sth and what? I tried sending a message before the build method and after it, those messages got send in the channel, but when I try to send a message inside the .then it won't be send... What is the problem then when the code isn't executed?

**Comment by L3-N0X** [comment]
Here you can see the whole code, but I don't think it is necessary, or? 
https://repl.it/@L3NOX/XP-BOT-1#index.js

**Comment by L3-N0X** [comment]
I´ve seen an error now, but don´t know if it´s affecting something:
`Fontconfig error: Cannot load default config file`
Is this the problem? And how to fix it?

**Comment by L3-N0X** [comment]
Hey, I found the problem! I copied the original Code and tried change only one thing and test it. And so the message doesn´t appear as soon as i set the Image to this URL. There must be the Error... But thanks for the help! 
Good npm Package btw!
