### ISSUE TITLE
[BUG] Canvas.Welcomer is not constructor

### ISSUE THREAD

**Issue by ibnusyawall** [DevSnowflake/canvacord#71]
```sh
var wellcome = new Canvas.Welcomer()
               ^

TypeError: Canvas.Welcomer is not a constructor
    at Object.<anonymous> (/data/data/com.termux/files/home/botntol2/cord.js:3:10)
```

my code:

```js
var Canvas = require('canvacord')

var wellcome = new Canvas.Welcomer()

wellcome.build()
  .then(buffer => {
        Canvas.write(buffer, 'result.png')
        console.log('success')
   })
```

**Comment by Snowflake107** [comment]
Install **discord-canvas** with `npm i discord-canvas` and run the code

**Comment by ibnusyawall** [comment]
Oke, i will try

**Comment by ibnusyawall** [comment]
and finally success, thank you

**Comment by trunglaptrinh** [comment]
```
const { Canvacord } = require("canvacord");

module.exports = (client) => {
    const channelId = "926668045068410913";
    // const rulesChannel = "927464314707783771";
    client.on("guildMemberAdd", async(member) => {
        const welcome = new Canvacord.Welcomer()
            .setUsername(member.user.username)
            .setDiscriminator(discriminator.user.username)
            .setAvatar(member.user.displayAvatarURL({ format: "png" }))
            .setColor("tittle", "#111111")
            .setColor("username-box", "#111111")
            .setColor("user-discriminator", "#111111")
            .setColor("message-box", "#111111")
            .setColor("boder", "#111111")
            .setColor("avatar", "#111111")
            .setbackgroung("https://i.imgur.com/WTQXVME.jpeg")
            .set(member.guild.memberCount);

        const channel = member.guild.channels.cache.get(channelId);
        channel.send(welcome);
    });
};
```

It print "TypeError: Canvacord.Welcomer is not a constructor"

**Comment by sujalgoel** [comment]
> 

Install discord-canvas using **`npm i discord-canvas`** and try again.

**Comment by sujalgoel** [comment]
> ```
> const { Canvacord } = require("canvacord");
> 
> module.exports = (client) => {
>     const channelId = "926668045068410913";
>     // const rulesChannel = "927464314707783771";
>     client.on("guildMemberAdd", async(member) => {
>         const welcome = new Canvacord.Welcomer()
>             .setUsername(member.user.username)
>             .setDiscriminator(discriminator.user.username)
>             .setAvatar(member.user.displayAvatarURL({ format: "png" }))
>             .setColor("tittle", "#111111")
>             .setColor("username-box", "#111111")
>             .setColor("user-discriminator", "#111111")
>             .setColor("message-box", "#111111")
>             .setColor("boder", "#111111")
>             .setColor("avatar", "#111111")
>             .setbackgroung("https://i.imgur.com/WTQXVME.jpeg")
>             .set(member.guild.memberCount);
> 
>         const channel = member.guild.channels.cache.get(channelId);
>         channel.send(welcome);
>     });
> };
> ```
> 
> It print "TypeError: Canvacord.Welcomer is not a constructor"

Install discord-canvas using **`npm i discord-canvas`** and try again.

**Comment by AboMeezO** [comment]
tried to install discord-canvas and  the console got spammed with errors

**Comment by twlite** [comment]
> tried to install discord-canvas and the console got spammed with errors

in version six, welcomer was removed. Please take a look at this example instead https://canvacord.neplex.dev/examples/builders/greetings-card
