### ISSUE TITLE
How to set custom background?

### ISSUE THREAD

**Issue by styleryt** [DevSnowflake/canvacord#73]
Hello, i wanted to know how to make my own background, already tried everything, and .setBackground, and
```js
.background.type("image")
.background.image(data)
```
And... nothing worked

Canvacord latest, help pls, thanks in advance!

**Comment by Snowflake107** [comment]
it's ```js
.setBackground("IMAGE", "YOUR_IMAGE_PATH_OR_LINK_OR_BUFFER")
```

**Comment by styleryt** [comment]
Thx! :)
