### ISSUE TITLE
Help: Custom Fonts

### ISSUE THREAD

**Issue by AdamTmHun** [DevSnowflake/canvacord#83]
I want to edit fonts, thats all. I found a method 
`Rank#registerFonts` but I don’t know how to use that and if that is what makes custom fonts possible.

**Comment by Snowflake107** [comment]
first, `.registerFonts` and in `.build`, specify the font you want to use

**Comment by AdamTmHun** [comment]
And the documentation said that the `.regiterFonts` takes up one argument, an array of fonts. Can you give me an example of this, since I don’t really understand what is going on there.

**Comment by Snowflake107** [comment]
@AdamTmHun you need to do something like this

```js
const fonts = [
    { path: "./myfontFile", face: { family: "blah", weight: "blah", style: "blah" } }
];

// instantiate Rank and do this
.registerFonts(fonts);

// finally
await card.build({ fontX: "blah", fontY: "blah" });
```

**Comment by Snowflake107** [comment]
I guess this issue is resolved? If not, feel free to `re-open` this
