### ISSUE TITLE
No typescript typings.

### ISSUE THREAD

**Issue by PraveshKunwar** [DevSnowflake/canvacord#85]
Hello, have an issue with this package. I like the idea behind the package but when I tried using this in typescript, I got no typing support. Can we get more support for this?

**Comment by Snowflake107** [comment]
yeah typings are planned for v6

**Comment by PraveshKunwar** [comment]
Any idea on when it might be released?

**Comment by Snowflake107** [comment]
might take few months

**Comment by PraveshKunwar** [comment]
alright
