### ISSUE TITLE
??

### ISSUE THREAD

**Issue by hardiantojek93** [DevSnowflake/canvacord#86]
![Screenshot_2021-04-11-09-15-59-825_com android chrome](https://user-images.githubusercontent.com/71861395/114288978-c0832180-9aa6-11eb-8de2-21de5c5a4b09.jpg)

**Comment by Snowflake107** [comment]
you are using `discord-canvas`
![image](https://user-images.githubusercontent.com/46562212/114299239-f392d880-9ad9-11eb-8b3a-adfb92ffbfc0.png)
