### ISSUE TITLE
How to remove server msg and box

### ISSUE THREAD

**Issue by BlackKnight683** [DevSnowflake/canvacord#87]
Hi im using the welcomer feature of canvacord whose base requires discord canvas (issue #53 )

I would like to know how can i get rid of the server welcome box and the text inside it

Im referring to this
![image](https://user-images.githubusercontent.com/75422863/114670661-8a8ea900-9d03-11eb-9b20-5ef0a698557f.png)

ik that it requires editing node_modules, but what to edit there? 0.0

**Comment by zyrouge** [comment]
It's not recommended to edit files in node_modules. Best is to make your own if you want to customise it :) (Maybe expect a new welcome card in the the upcoming versions)

**Comment by BlackKnight683** [comment]
Alrighty, Thanks for the help :D
