### ISSUE TITLE
[BUG] canvacord.Spotify() not working 

### ISSUE THREAD

**Issue by Naozumi520** [DevSnowflake/canvacord#93]
**Describe the bug**
Error 404 when generate the card.
 
**To Reproduce**
1. Generate a card
2. Error 404

**Expected behavior**
The card will be generated.

**Screenshots**
![image](https://user-images.githubusercontent.com/52615455/119221905-3b1e7280-bb24-11eb-9f06-27073af35475.png)
 - Node Version: [v16.0.0]
 - Library Version: [^5.2.0]

**Comment by Snowflake107** [comment]
This is the issue of your image url itself
